/*.g
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gol.groovy

class App {

    static void main(String[] args) {

        def seed = new Random()
        seed.setSeed(System.currentTimeMillis())
        def grid = Grid.newInstance(10, 10, seed)

        int generations = 10
        for (int g = 0; g < generations; g++) {
            def cells = grid.cells
            StringBuilder display = new StringBuilder()
            System.out.println("Generation " + g)
            System.out.println(generateGrid(cells, display))
            grid.update()
        }
    }

    private static String generateGrid(Cell[][] cells, StringBuilder display) {
        for (int gridRow = 0; gridRow < cells.length; gridRow++) {

            for (int gridColumn = 0; gridColumn < cells[gridRow].length; gridColumn++) {

                display.append(cells[gridRow][gridColumn].getState().getStateCode()).append("\t")
            }
            display.append("\n")
        }

        return display.toString();
    }
}
